// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartService.Infrastructure.Persistence;

#nullable disable

namespace SmartService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324163227_RedesignMasterFlow")]
    partial class RedesignMasterFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartService.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.AgentCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceAgentId")
                        .HasColumnType("uuid");

                    b.Property<List<Guid>>("ServiceIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAgentId");

                    b.ToTable("AgentCapabilities");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.CommissionSettings", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("DepositPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ServiceDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionId");

                    b.ToTable("CommissionSettings");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.CompletionEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.ToTable("CompletionEvidences");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.MatchingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MatchingScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ServiceAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceRequestId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("ServiceRequestId1");

                    b.ToTable("MatchingResults");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.Payout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Payouts");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.PriceAdjustmentRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ProcessedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PriceAdjustmentRequests");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ServiceAgents");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceAnalysis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ComplexityLevel")
                        .HasColumnType("integer");

                    b.Property<string>("ProblemDiagnosis")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("RiskExplanation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("SafetyAdvice")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("UrgencyLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId")
                        .IsUnique();

                    b.ToTable("ServiceAnalyses");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceRequestId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("ServiceRequestId1");

                    b.ToTable("ServiceAttachments");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int[]>("ComplexityRange")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer[]")
                        .HasDefaultValueSql("ARRAY[1,3]");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("EstimatedDuration")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDangerous")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("ServiceDefinitions");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ServiceFeedbacks");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AddressText")
                        .HasColumnType("text");

                    b.Property<Guid?>("AssignedProviderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CommissionRate")
                        .HasPrecision(5, 4)
                        .HasColumnType("numeric(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EstimatedDuration")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EstimatedPrice")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsDepositPaid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("OcrExtractedText")
                        .HasColumnType("text");

                    b.Property<Guid?>("ServiceDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<bool>("WasAnalyzedByAI")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("ServiceDefinitionId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartService.Infrastructure.Auth.AuthData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AuthData");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.AgentCapability", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceAgent", null)
                        .WithMany("Capabilities")
                        .HasForeignKey("ServiceAgentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SmartService.Domain.ValueObjects.ServiceComplexity", "MaxComplexity", b1 =>
                        {
                            b1.Property<Guid>("AgentCapabilityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("MaxComplexityLevel");

                            b1.HasKey("AgentCapabilityId");

                            b1.ToTable("AgentCapabilities");

                            b1.WithOwner()
                                .HasForeignKey("AgentCapabilityId");
                        });

                    b.Navigation("MaxComplexity")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.Assignment", b =>
                {
                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "EstimatedCost", b1 =>
                        {
                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("EstimatedCost_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("EstimatedCost_Currency");

                            b1.HasKey("AssignmentId");

                            b1.ToTable("Assignments");

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId");
                        });

                    b.Navigation("EstimatedCost")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.CommissionSettings", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceDefinition", null)
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.CompletionEvidence", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.MatchingResult", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartService.Domain.Entities.ServiceRequest", null)
                        .WithMany("MatchingResults")
                        .HasForeignKey("ServiceRequestId1");

                    b.OwnsOne("SmartService.Domain.ValueObjects.ServiceComplexity", "SupportedComplexity", b1 =>
                        {
                            b1.Property<Guid>("MatchingResultId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("SupportedComplexityLevel");

                            b1.HasKey("MatchingResultId");

                            b1.ToTable("MatchingResults");

                            b1.WithOwner()
                                .HasForeignKey("MatchingResultId");
                        });

                    b.Navigation("SupportedComplexity")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.Payout", b =>
                {
                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "CommissionAmount", b1 =>
                        {
                            b1.Property<Guid>("PayoutId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CommissionAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("CommissionAmount_Currency");

                            b1.HasKey("PayoutId");

                            b1.ToTable("Payouts");

                            b1.WithOwner()
                                .HasForeignKey("PayoutId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "TotalAmount", b1 =>
                        {
                            b1.Property<Guid>("PayoutId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("TotalAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("TotalAmount_Currency");

                            b1.HasKey("PayoutId");

                            b1.ToTable("Payouts");

                            b1.WithOwner()
                                .HasForeignKey("PayoutId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "WorkerAmount", b1 =>
                        {
                            b1.Property<Guid>("PayoutId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("WorkerAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("WorkerAmount_Currency");

                            b1.HasKey("PayoutId");

                            b1.ToTable("Payouts");

                            b1.WithOwner()
                                .HasForeignKey("PayoutId");
                        });

                    b.Navigation("CommissionAmount")
                        .IsRequired();

                    b.Navigation("TotalAmount")
                        .IsRequired();

                    b.Navigation("WorkerAmount")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.PriceAdjustmentRequest", b =>
                {
                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "NewPrice", b1 =>
                        {
                            b1.Property<Guid>("PriceAdjustmentRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("NewPrice_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("NewPrice_Currency");

                            b1.HasKey("PriceAdjustmentRequestId");

                            b1.ToTable("PriceAdjustmentRequests");

                            b1.WithOwner()
                                .HasForeignKey("PriceAdjustmentRequestId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "OldPrice", b1 =>
                        {
                            b1.Property<Guid>("PriceAdjustmentRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("OldPrice_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("OldPrice_Currency");

                            b1.HasKey("PriceAdjustmentRequestId");

                            b1.ToTable("PriceAdjustmentRequests");

                            b1.WithOwner()
                                .HasForeignKey("PriceAdjustmentRequestId");
                        });

                    b.Navigation("NewPrice")
                        .IsRequired();

                    b.Navigation("OldPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceAttachment", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartService.Domain.Entities.ServiceRequest", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ServiceRequestId1");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceDefinition", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceRequest", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceDefinition", null)
                        .WithMany()
                        .HasForeignKey("ServiceDefinitionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "CommissionAmount", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("CommissionAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("CommissionAmount_Currency");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.ServiceComplexity", "Complexity", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("ComplexityLevel");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "DepositAmount", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("DepositAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("DepositAmount_Currency");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "EstimatedCost", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("EstimatedCost_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("EstimatedCost_Currency");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "FinalAmountPaid", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("FinalAmountPaid_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("FinalAmountPaid_Currency");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "FinalPrice", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("FinalPrice_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("FinalPrice_Currency");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "WorkerAmount", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("WorkerAmount_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("WorkerAmount_Currency");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.Navigation("CommissionAmount");

                    b.Navigation("Complexity")
                        .IsRequired();

                    b.Navigation("DepositAmount");

                    b.Navigation("EstimatedCost");

                    b.Navigation("FinalAmountPaid");

                    b.Navigation("FinalPrice");

                    b.Navigation("WorkerAmount");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceAgent", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("MatchingResults");
                });
#pragma warning restore 612, 618
        }
    }
}
