// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartService.Infrastructure.Persistence;

#nullable disable

namespace SmartService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260126084402_InitialCreate1")]
    partial class InitialCreate1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartService.Domain.Entities.ActivityLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ActivityLogs");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.AgentCapability", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceAgentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAgentId");

                    b.ToTable("AgentCapabilities");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.MatchingResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsRecommended")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MatchingScore")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ServiceAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceRequestId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("ServiceRequestId1");

                    b.ToTable("MatchingResults");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceAgent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("ServiceAgents");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ServiceRequestId1")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("ServiceRequestId1");

                    b.ToTable("ServiceAttachments");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("ServiceCategories");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceFeedback", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<Guid>("ServiceRequestId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ServiceFeedbacks");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedProviderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.AgentCapability", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceAgent", null)
                        .WithMany("Capabilities")
                        .HasForeignKey("ServiceAgentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("SmartService.Domain.ValueObjects.ServiceComplexity", "MaxComplexity", b1 =>
                        {
                            b1.Property<Guid>("AgentCapabilityId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("MaxComplexityLevel");

                            b1.HasKey("AgentCapabilityId");

                            b1.ToTable("AgentCapabilities");

                            b1.WithOwner()
                                .HasForeignKey("AgentCapabilityId");
                        });

                    b.Navigation("MaxComplexity")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.Assignment", b =>
                {
                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "EstimatedCost", b1 =>
                        {
                            b1.Property<Guid>("AssignmentId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("EstimatedCost_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("EstimatedCost_Currency");

                            b1.HasKey("AssignmentId");

                            b1.ToTable("Assignments");

                            b1.WithOwner()
                                .HasForeignKey("AssignmentId");
                        });

                    b.Navigation("EstimatedCost")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.MatchingResult", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartService.Domain.Entities.ServiceRequest", null)
                        .WithMany("MatchingResults")
                        .HasForeignKey("ServiceRequestId1");

                    b.OwnsOne("SmartService.Domain.ValueObjects.ServiceComplexity", "SupportedComplexity", b1 =>
                        {
                            b1.Property<Guid>("MatchingResultId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("SupportedComplexityLevel");

                            b1.HasKey("MatchingResultId");

                            b1.ToTable("MatchingResults");

                            b1.WithOwner()
                                .HasForeignKey("MatchingResultId");
                        });

                    b.Navigation("SupportedComplexity")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceAttachment", b =>
                {
                    b.HasOne("SmartService.Domain.Entities.ServiceRequest", null)
                        .WithMany()
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartService.Domain.Entities.ServiceRequest", null)
                        .WithMany("Attachments")
                        .HasForeignKey("ServiceRequestId1");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceRequest", b =>
                {
                    b.OwnsOne("SmartService.Domain.ValueObjects.ServiceComplexity", "Complexity", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Level")
                                .HasColumnType("integer")
                                .HasColumnName("ComplexityLevel");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.OwnsOne("SmartService.Domain.ValueObjects.Money", "EstimatedCost", b1 =>
                        {
                            b1.Property<Guid>("ServiceRequestId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("numeric(18,2)")
                                .HasColumnName("EstimatedCost_Amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("EstimatedCost_Currency");

                            b1.HasKey("ServiceRequestId");

                            b1.ToTable("ServiceRequests");

                            b1.WithOwner()
                                .HasForeignKey("ServiceRequestId");
                        });

                    b.Navigation("Complexity")
                        .IsRequired();

                    b.Navigation("EstimatedCost");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceAgent", b =>
                {
                    b.Navigation("Capabilities");
                });

            modelBuilder.Entity("SmartService.Domain.Entities.ServiceRequest", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("MatchingResults");
                });
#pragma warning restore 612, 618
        }
    }
}
