using SmartService.Domain.ValueObjects;

namespace SmartService.Domain.Entities;

/// <summary>
/// Represents a matching evaluation result
/// between a service request and a service agent.
/// 
/// Matching results are generated by system logic
/// or staff decision support and do NOT imply assignment.
/// 
/// Used to assist staff or customers in selecting agents.
/// </summary>
public class MatchingResult
{
    public Guid Id { get; private set; }
    public Guid ServiceRequestId { get; private set; }
    public Guid ServiceAgentId { get; private set; }

    public ServiceComplexity SupportedComplexity { get; private set; } = null;
    public decimal MatchingScore { get; private set; }
    public bool IsRecommended { get; private set; }

    private MatchingResult() { }

    private MatchingResult(
        Guid serviceRequestId,
        Guid serviceAgentId,
        ServiceComplexity supportedComplexity,
        decimal matchingScore,
        bool isRecommended)
    {
        Id = Guid.NewGuid();
        ServiceRequestId = serviceRequestId;
        ServiceAgentId = serviceAgentId;
        SupportedComplexity = supportedComplexity;
        MatchingScore = matchingScore;
        IsRecommended = isRecommended;
    }

    public static MatchingResult Create(
        Guid serviceRequestId,
        Guid serviceAgentId,
        ServiceComplexity supportedComplexity,
        decimal score,
        bool recommended)
        => new(serviceRequestId, serviceAgentId, supportedComplexity, score, recommended);
}
